language: cpp

git:
  depth: 3

sudo: required
dist: trusty
compiler: gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang

# Install deps
install:
  - bash .travis/install-deps.sh

# Build steps
script:
  - mkdir build/ && cd build/
  - cmake ..
  - make inkscape_version
  - make

# Run tests
after_success:
  - make test
  - cd ./bin/inkscape --version
