language: cpp

git:
  depth: 3

sudo: required
dist: trusty
compiler: gcc

matrix:
  include:
    - os: osx
      osx_image: xcode8
      compiler: clang

# Install deps
install:
  - bash .travis/install-deps.sh
  - bash download-gtest.sh

# Build steps
script:
  - mkdir build/ && cd build/
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake .. ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then cmake -DLDFLAGS=-L/usr/local/opt/gettext/lib -DCPPFLAGS=-I/usr/local/opt/gettext/include .. ; fi
  - make inkscape_version
  - make

# Run tests
after_success:
  - make test
  - ./bin/inkscape --version
